/* Casos de test del Level 3 de ESTA app (Future Tenses).
   full: respuesta modelo SIN contracciones · pos: deben ACEPTARSE · neg: deben FALLAR */
module.exports = {
  will_l3_0: { full: "I think it will rain tomorrow.",
    pos: ["I think it's going to rain tomorrow.", "I think that it will rain tomorrow.", "Tomorrow I think it'll rain.", "I think itll rain tomorrow"],
    neg: ["I think it rains tomorrow.", "I think it will rains tomorrow.", "I think it will to rain tomorrow.", "I think will rain tomorrow.", "I think it going to rain tomorrow.", "I think it is raining tomorrow."] },
  will_l3_1: { full: "I will help you with your homework.",
    pos: ["I'll help you with the homework.", "Ill help you with your homework", "I will help you do your homework."],
    neg: ["I help you with your homework.", "I will to help you with your homework.", "I will helping you with your homework.", "I am going help you with your homework.", "I will help you with your homeworks.", "I will help to you with your homework."] },
  will_l3_2: { full: "I promise I will not tell anyone.",
    pos: ["I promise I won't tell anybody.", "I promise not to tell anyone.", "I promise that I'll never tell anyone.", "I promise I will tell nobody.", "I promise I wont tell anyone"],
    neg: ["I promise I don't tell anyone.", "I promise I won't tell nobody.", "I promise I will not to tell anyone.", "I promise I'll not tell anyone.", "I promise I am not telling anyone.", "I promise to not telling anyone."] },
  will_l3_3: { full: "Will you help me with this box?",
    pos: ["Will you help me with this box, please?", "will you help me with this box"],
    neg: ["Do you help me with this box?", "You will help me with this box?", "Will you to help me with this box?", "Will you helping me with this box?", "Will you help me with that box?", "Are you help me with this box?"] },
  will_l3_4: { full: "They will probably arrive late.",
    pos: ["They'll probably be late.", "They are probably going to arrive late.", "Probably they will arrive late.", "They will probably get here late."],
    neg: ["They probably arrive late.", "They will probably arriving late.", "They probably will to arrive late.", "They will arrive probably late.", "They will probably arrive lately.", "They are going probably to arrive late."] },
  will_l3_5: { full: "I am sure you will pass.",
    pos: ["I am sure that you will pass the exam.", "I'm sure you'll pass.", "Im sure youll pass your test", "I'm sure you're going to pass."],
    neg: ["I am sure you pass.", "I am sure you will to pass.", "I am sure you will passed.", "I sure you will pass.", "I am sure you will approve.", "I am sure you will pass on."] },
  will_l3_6: { full: "I will bring you a glass of water.",
    pos: ["I'll get you a glass of water.", "I will bring a glass of water for you."],
    neg: ["I bring you a glass of water.", "I will brought you a glass of water.", "I will bring to you a glass of water.", "I will bring you a glass water.", "I will bring you a glass with water.", "I am bringing you a glass of water."] },
  will_l3_7: { full: "Robots will do the housework in the future.",
    pos: ["In the future, robots will do the housework.", "The robots will do the household chores in the future.", "Robots will do the chores in the future."],
    neg: ["Robots do the housework in the future.", "Robots will make the housework in the future.", "Robots will doing the housework in the future.", "Robots will do the houseworks in the future.", "Robots are doing the housework in the future.", "Robots will do the housework in future the."] },
  will_l3_8: { full: "I do not think he will come.",
    pos: ["I don't think she's going to come.", "I think he won't come.", "I dont think he will come", "I don't think that she will come."],
    neg: ["I don't think he comes.", "I don't think he will comes.", "I think he doesn't come.", "I don't think he will to come.", "I not think he will come.", "I don't think he going to come."] },
  will_l3_9: { full: "I will be sixteen next month.",
    pos: ["I'll turn sixteen next month.", "I'm sixteen next month.", "Next month I'll be 16.", "I'm turning 16 next month."],
    neg: ["I will have sixteen next month.", "I have sixteen years next month.", "I will be sixteen last month.", "I will sixteen next month.", "I will be sixteen years next month.", "I will be sixteen the next month."] },

  going_l3_0: { full: "I am going to study medicine.",
    pos: ["I'm going to study Medicine.", "Im going to study medicine"],
    neg: ["I going to study medicine.", "I am going study medicine.", "I am go to study medicine.", "I am going to studying medicine.", "I will going to study medicine.", "I'm going to study the medicine."] },
  going_l3_1: { full: "Look at those clouds! It is going to rain.",
    pos: ["Look at those black clouds! It's going to rain.", "Look at those clouds, it's going to rain", "look at those dark clouds its going to rain"],
    neg: ["Look at those clouds! It will rain.", "Look at those clouds! It rains.", "Look at those clouds! Is going to rain.", "Look those clouds! It is going to rain.", "Look at these clouds! It is going to rain.", "Look at those clouds! It is going to raining."] },
  going_l3_2: { full: "Are you going to go to Ana's party?",
    pos: ["Are you going to Ana's party?", "are you going to go to anas party"],
    neg: ["Do you go to Ana's party?", "You are going to go to Ana's party?", "Are you going to Ana party?", "Are you go to Ana's party?", "Are you going to going to Ana's party?", "Will you going to Ana's party?"] },
  going_l3_3: { full: "We are not going to buy a new car.",
    pos: ["We aren't going to buy a new car.", "We're not going to buy a new car.", "Were not going to buy a new car"],
    neg: ["We don't going to buy a new car.", "We are not going to buy a car new.", "We are going not to buy a new car.", "We not going to buy a new car.", "We are not going to bought a new car.", "We won't going to buy a new car."] },
  going_l3_4: { full: "Be careful! You are going to fall.",
    pos: ["Watch out! You're going to fall over.", "Careful, you are going to fall down!", "Look out! Youre going to fall"],
    neg: ["Be careful! You will fall.", "Be careful! You fall.", "Be careful! You are going to falling.", "Be careful! You going to fall.", "Be careful! You're going to fell.", "Be careful! You're going to fall you."] },
  going_l3_5: { full: "My brother is going to start working in September.",
    pos: ["In September my brother is going to start work.", "My brother's going to begin working in September.", "My brother is going to start to work in September"],
    neg: ["My brother is going to start work on September.", "My brother is going to starting working in September.", "My brother going to start working in September.", "My brother are going to start working in September.", "My brother is going to start working in the September.", "My brother starts working in September."] },
  going_l3_6: { full: "What are you going to do this weekend?",
    pos: ["What are you doing this weekend?", "This weekend, what are you going to do?"],
    neg: ["What do you do this weekend?", "What you are going to do this weekend?", "What are you going to make this weekend?", "What are you going do this weekend?", "What are you going to do the weekend?", "What will you going to do this weekend?"] },
  going_l3_7: { full: "They are going to have a baby.",
    pos: ["They're having a baby.", "Theyre going to have a baby"],
    neg: ["They will have a baby.", "They are going to have baby.", "They going to have a baby.", "They are going to has a baby.", "They are going to having a baby.", "They have a baby."] },
  going_l3_8: { full: "This summer I am going to learn to swim.",
    pos: ["I'm going to learn how to swim this summer.", "I am going to learn swimming this summer.", "This summer Im going to learn to swim"],
    neg: ["This summer I am going to learn swim.", "This summer I am going to learn to swimming.", "This summer I will going to learn to swim.", "This summer I going to learn to swim.", "This summer I am going to teach to swim.", "The summer I am going to learn to swim."] },
  going_l3_9: { full: "I am not going to watch that film.",
    pos: ["I'm not going to see that movie.", "I am not going to watch that movie."],
    neg: ["I don't going to watch that film.", "I am not going to watch this film.", "I am going to not watch that film.", "I not going to watch that film.", "I am not going to watching that film.", "I won't going to watch that film."] },

  wvg_l3_0: { full: "It is cold. I will close the window.",
    pos: ["It's cold. I'll shut the window.", "It is cold, I will close the window", "Its cold Ill close the window"],
    neg: ["It is cold. I close the window.", "It is cold. I am going to close the window.", "It is cold. I will to close the window.", "Is cold. I will close the window.", "It makes cold. I will close the window.", "It is cold. I will closing the window."] },
  wvg_l3_1: { full: "I have already decided: I am going to study in England.",
    pos: ["I've decided: I'm going to study in England.", "I have already decided, I am going to study in England"],
    neg: ["I have already decided: I will study in England.", "I have already decided: I study in England.", "I already decide: I am going to study in England.", "I have already decided: I going to study in England.", "I have already decided: I am going to study at England.", "I have decided already: I am going to studying in England."] },
  wvg_l3_2: { full: "Look! That boy is going to fall.",
    pos: ["Look! That child is going to fall over.", "Look, that kid's going to fall down!"],
    neg: ["Look! That boy will fall.", "Look! That boy falls.", "Look! That boy is going to falling.", "Look! That boy going to fall.", "Look! This boy is going to fall.", "Look! That boy is going to fall himself."] },
  wvg_l3_3: { full: "Shall I help you with the suitcases?",
    pos: ["Shall I help you with your bags?", "Do you want me to help you with the suitcases?", "Can I help you with your luggage?"],
    neg: ["Do I help you with the suitcases?", "Will I help you with the suitcases?", "Shall I to help you with the suitcases?", "Shall I helping you with the suitcases?", "I shall help you with the suitcases?", "Shall I help you with the luggages?"] },
  wvg_l3_4: { full: "I promise I will call you.",
    pos: ["I promise I'll phone you.", "I promise to call you.", "I promise that I will ring you."],
    neg: ["I promise I call you.", "I promise I am going to call you.", "I promise I will calling you.", "I promise I will to call you.", "I promise I will call to you.", "I promise I called you."] },
  wvg_l3_5: { full: "We have bought the tickets: we are going to go to Rome in August.",
    pos: ["We've bought the tickets: we're going to Rome in August.", "We have bought the tickets, in August we are going to visit Rome.", "We have bought the tickets: we're flying to Rome in August."],
    neg: ["We have bought the tickets: we will go to Rome in August.", "We have bought the tickets: we go to Rome in August.", "We bought the tickets: we are going to go to Rome on August.", "We have bought the tickets: we going to go to Rome in August.", "We have bought the tickets: we are going to go at Rome in August.", "We have buyed the tickets: we are going to go to Rome in August."] },
  wvg_l3_6: { full: "I think you will like this book.",
    pos: ["I think you're going to like this book.", "I think that you'll like this book."],
    neg: ["I think you like this book.", "I think you will likes this book.", "I think you will to like this book.", "I think you will like that book.", "I think you will liking this book.", "I think will you like this book."] },
  wvg_l3_7: { full: "Be careful! You are going to break the vase.",
    pos: ["Careful! You're going to break the vase.", "Watch out, you're going to break the vase!"],
    neg: ["Be careful! You will break the vase.", "Be careful! You break the vase.", "Be careful! You are going to broke the vase.", "Be careful! You going to break the vase.", "Be careful! You are going to breaking the vase.", "Be careful! You are going to break the glass."] },
  wvg_l3_8: { full: "It is late. I think I will go home.",
    pos: ["It's late. I think I'll go home.", "Its late I think Ill go home"],
    neg: ["It is late. I think I go home.", "It is late. I think I will go to home.", "It is late. I think I will going home.", "Is late. I think I will go home.", "It is late. I think I will went home.", "It is late. I think I will go at home."] },
  wvg_l3_9: { full: "I am not going to have dinner tonight because I am not hungry.",
    pos: ["I am not going to have dinner tonight as I am not hungry.", "I'm not going to eat dinner this evening because I'm not hungry.", "Tonight I'm not going to have supper because I'm not hungry."],
    neg: ["I am not going to have dinner tonight because I don't have hunger.", "I am not going to have dinner tonight because I have not hungry.", "I don't going to have dinner tonight because I'm not hungry.", "I am not going to dinner tonight because I am not hungry.", "I will not going to have dinner tonight because I'm not hungry.", "I am not going to have dinner tonight because I'm not hunger."] },

  fc_l3_0: { full: "This time tomorrow I will be flying to London.",
    pos: ["I'll be flying to London at this time tomorrow.", "At this time tomorrow I will be flying to London."],
    neg: ["This time tomorrow I will fly to London.", "This time tomorrow I will be fly to London.", "This time tomorrow I will flying to London.", "This time tomorrow I am flying to London.", "This time tomorrow I will be flying at London.", "This time tomorrow I will be flew to London."] },
  fc_l3_1: { full: "At eight we will be having dinner.",
    pos: ["We'll be having dinner at eight o'clock.", "We will be eating dinner at 8.", "At 8 pm we'll be having supper."],
    neg: ["At eight we will have dinner.", "At eight we will be have dinner.", "At eight we will having dinner.", "At eight we are having dinner.", "At eight we will be having dinner at nine.", "At eight we will be dinner."] },
  fc_l3_2: { full: "Will you be using the computer tonight?",
    pos: ["Are you going to use the computer this evening?", "Are you using the computer tonight?"],
    neg: ["Do you use the computer tonight?", "Will you use the computer tonight?", "Will you be use the computer tonight?", "Will you using the computer tonight?", "You will be using the computer tonight?", "Will you be using the computer yesterday?"] },
  fc_l3_3: { full: "I will not be working on Monday.",
    pos: ["I won't be working on Monday.", "I'm not working on Monday.", "On Monday I won't be working.", "I wont be working on monday"],
    neg: ["I don't work on Monday.", "I won't be work on Monday.", "I won't working on Monday.", "I will not working on Monday.", "I won't be working in Monday.", "I will be not working on Monday."] },
  fc_l3_4: { full: "In ten years' time I will be living in another country.",
    pos: ["In ten years I'll be living in a different country.", "I will be living in another country in ten years' time.", "In 10 years time I will live in another country."],
    neg: ["In ten years I am living in another country.", "In ten years I will be live in another country.", "In ten years I will living in another country.", "Ten years ago I will be living in another country.", "In ten years I will be living in other country.", "In ten years I will be living on another country."] },
  fc_l3_5: { full: "What will you be doing at five tomorrow?",
    pos: ["What will you be doing tomorrow at five?", "What will you be doing at 5 tomorrow afternoon?", "Tomorrow at five, what will you be doing?"],
    neg: ["What will you do at five tomorrow?", "What are you doing at five tomorrow?", "What will you be do at five tomorrow?", "What you will be doing at five tomorrow?", "What will you doing at five tomorrow?", "What will you be making at five tomorrow?"] },
  fc_l3_6: { full: "I will be studying all day tomorrow.",
    pos: ["Tomorrow I'll be studying all day.", "I'll be studying the whole day tomorrow."],
    neg: ["I will study all day tomorrow.", "I will be study all day tomorrow.", "I will studying all day tomorrow.", "I am studying all day tomorrow.", "I will be studying all the day tomorrow.", "I will be studying every day tomorrow."] },
  fc_l3_7: { full: "When you arrive, we will be watching the match.",
    pos: ["We'll be watching the game when you get here.", "When you come, we will be watching the match."],
    neg: ["When you will arrive, we will be watching the match.", "When you arrive, we will watch the match.", "When you arrive, we will be watch the match.", "When you arrive, we are watching the match.", "When you arrived, we will be watching the match.", "When you arrive, we will be seeing the match."] },
  fc_l3_8: { full: "This time next year she will be working in London.",
    pos: ["He'll be working in London at this time next year.", "She will be working in London this time next year."],
    neg: ["This time next year she will work in London.", "This time next year she will be work in London.", "This time next year she works in London.", "This time next year she will working in London.", "This time last year she will be working in London.", "This time next year she will be working at London."] },
  fc_l3_9: { full: "Do not call me at nine: I will be sleeping.",
    pos: ["Don't phone me at nine because I'll be asleep.", "Don't call me at 9, I'll be sleeping.", "Dont ring me at nine Ill be sleeping"],
    neg: ["Don't call me at nine: I will sleep.", "Don't call me at nine: I am sleeping.", "Don't call me at nine: I will be sleep.", "Don't call me at nine: I will sleeping.", "Don't call to me at nine: I will be sleeping.", "Not call me at nine: I will be sleeping."] },

  fp_l3_0: { full: "By ten I will have finished my homework.",
    pos: ["I'll have finished my homework by ten o'clock.", "By 10 I'll have finished the homework."],
    neg: ["By ten I will finish my homework.", "By ten I will have finish my homework.", "By ten I will have finishing my homework.", "By ten I have finished my homework.", "For ten I will have finished my homework.", "Until ten I will have finished my homework."] },
  fp_l3_1: { full: "When you arrive, we will have already left.",
    pos: ["By the time you get here, we'll have left.", "We will have already gone when you arrive.", "When you arrive we'll already have left"],
    neg: ["When you will arrive, we will have already left.", "When you arrive, we will already leave.", "When you arrive, we will have already leave.", "When you arrive, we will have already leaved.", "When you arrive, we have already left.", "When you arrive, we will be already left."] },
  fp_l3_2: { full: "By 2030 I will have finished university.",
    pos: ["I'll have graduated from university by 2030.", "By 2030 I will have left university."],
    neg: ["By 2030 I will finish university.", "By 2030 I will have finish university.", "By 2030 I have finished university.", "For 2030 I will have finished university.", "By 2030 I will have finished the university.", "In 2030 I will have finish university."] },
  fp_l3_3: { full: "Will you have read the book by Friday?",
    pos: ["will you have read the book by friday"],
    neg: ["Will you read the book by Friday?", "Will you have readed the book by Friday?", "Will you have read the book for Friday?", "You will have read the book by Friday?", "Have you read the book by Friday?", "Will you have read the book until Friday?"] },
  fp_l3_4: { full: "They will not have finished the bridge by the summer.",
    pos: ["They won't have finished the bridge by summer.", "By the summer they won't have finished the bridge."],
    neg: ["They won't finish the bridge by the summer.", "They won't have finish the bridge by the summer.", "They won't have finished the bridge for the summer.", "They haven't finished the bridge by the summer.", "They won't have finished the bridge until the summer.", "They will not finished the bridge by the summer."] },
  fp_l3_5: { full: "Next month we will have lived here for ten years.",
    pos: ["Next month we'll have been living here for ten years.", "We will have lived here for 10 years next month.", "Next month we will have lived here ten years."],
    neg: ["Next month we will live here for ten years.", "Next month we have lived here for ten years.", "Next month we will have live here for ten years.", "Next month we will have lived here since ten years.", "Next month we will have lived here during ten years.", "Last month we will have lived here for ten years."] },
  fp_l3_6: { full: "By the time the teacher arrives, we will have finished the exam.",
    pos: ["We'll have finished the exam by the time the teacher gets here.", "By the time the teacher comes, we will have done the test."],
    neg: ["By the time the teacher will arrive, we will have finished the exam.", "By the time the teacher arrives, we will finish the exam.", "By the time the teacher arrives, we will have finish the exam.", "By the time the teacher arrive, we will have finished the exam.", "By the time the teacher arrives, we have finished the exam.", "When the teacher arrives, we will have finished the examen."] },
  fp_l3_7: { full: "This time tomorrow I will have done the exam.",
    pos: ["By this time tomorrow I'll have already done the exam.", "This time tomorrow I will have taken the test.", "I will have done the exam by this time tomorrow."],
    neg: ["This time tomorrow I will do the exam.", "This time tomorrow I will be doing the exam.", "This time tomorrow I will have did the exam.", "This time tomorrow I will have made the exam.", "This time tomorrow I have done the exam.", "This time yesterday I will have done the exam."] },
  fp_l3_8: { full: "By the end of the year she will have read ten books.",
    pos: ["He will have read ten books by the end of the school year.", "By the end of the course she'll have read 10 books."],
    neg: ["By the end of the year she will read ten books.", "By the end of the year she will have readed ten books.", "By the end of the year she has read ten books.", "At the end of the year she will has read ten books.", "By the end of the year she will have read ten book.", "By the end of the year she will has read ten books."] },
  fp_l3_9: { full: "By then, they will have already forgotten about us.",
    pos: ["By then they'll have forgotten us.", "They will have already forgotten about us by then.", "By then theyll already have forgotten about us"],
    neg: ["By then, they will already forget about us.", "By then, they will have already forgot about us.", "By then, they have already forgotten about us.", "By then, they will have already forgotten of us.", "By then, they will have already forgetten about us.", "Until then, they will have already forgotten about us."] },

  pres_l3_0: { full: "The train leaves at eight.",
    pos: ["The train departs at 8 o'clock.", "The train is leaving at eight.", "The train leaves at 8:00"],
    neg: ["The train will leave at eight.", "The train leave at eight.", "The train leaves on eight.", "The train is going to leave at eight.", "The train left at eight.", "The train leaves at nine."] },
  pres_l3_1: { full: "I am having dinner with my grandparents tomorrow.",
    pos: ["Tomorrow I'm having dinner with my grandparents.", "I'm going to have dinner with my grandparents tomorrow.", "I am having supper with my grandma and grandpa tomorrow."],
    neg: ["I have dinner with my grandparents tomorrow.", "I am having dinner with my grandparents yesterday.", "I am have dinner with my grandparents tomorrow.", "I having dinner with my grandparents tomorrow.", "I am dinnering with my grandparents tomorrow.", "I am having dinner with my grandfathers tomorrow."] },
  pres_l3_2: { full: "I will call you when I get home.",
    pos: ["When I get home, I'll phone you.", "I'll ring you when I get back home.", "I will call you when I arrive home."],
    neg: ["I will call you when I will get home.", "I call you when I get home.", "I will call you when I got home.", "I will call you when I get to home.", "I will call to you when I get home.", "I will calling you when I get home."] },
  pres_l3_3: { full: "What time does the film start?",
    pos: ["When does the movie begin?", "What time is the film starting?"],
    neg: ["What time the film starts?", "What time does the film starts?", "What time will the film to start?", "What hour does the film start?", "What time do the film start?", "What time does start the film?"] },
  pres_l3_4: { full: "What are you doing this weekend?",
    pos: ["What are you going to do this weekend?", "This weekend, what are you doing?"],
    neg: ["What do you do this weekend?", "What you are doing this weekend?", "What are you making this weekend?", "What are you do this weekend?", "What are you doing the weekend?", "What did you do this weekend?"] },
  pres_l3_5: { full: "Classes start on Monday.",
    pos: ["Lessons begin on Monday.", "School starts on Monday.", "On Monday classes start.", "Classes are starting on Monday."],
    neg: ["Classes will to start on Monday.", "Classes starts on Monday.", "Classes start in Monday.", "Classes start the Monday.", "The classes start on Monday of.", "Classes started on Monday."] },
  pres_l3_6: { full: "We will not go out until it stops raining.",
    pos: ["We're not going out until the rain stops.", "We won't go out until it has stopped raining.", "We wont go out until it stops raining"],
    neg: ["We won't go out until it will stop raining.", "We won't go out until it stops to rain.", "We won't go out until it doesn't stop raining.", "We don't go out until it stops raining.", "We won't go until it stops raining out.", "We won't go out until it stop raining."] },
  pres_l3_7: { full: "I am playing tennis with Pablo this afternoon.",
    pos: ["This afternoon I'm going to play tennis with Pablo.", "I'm playing tennis with Pablo this evening."],
    neg: ["I play tennis with Pablo this afternoon.", "I am playing the tennis with Pablo this afternoon.", "I am play tennis with Pablo this afternoon.", "I playing tennis with Pablo this afternoon.", "I am playing to tennis with Pablo this afternoon.", "I am playing tennis with Pablo yesterday afternoon."] },
  pres_l3_8: { full: "As soon as I finish the exam, I will send you a message.",
    pos: ["I'll text you as soon as I finish the exam.", "When I have finished the test, I will send you a text.", "As soon as I finish the exam I'll send a message to you."],
    neg: ["As soon as I will finish the exam, I will send you a message.", "As soon as I finish the exam, I send you a message.", "As soon as I finished the exam, I will send you a message.", "As soon as I finish the exam, I will sent you a message.", "As soon as I finish the exam, I will send to you a message.", "As soon I finish the exam, I will send you a message."] },
  pres_l3_9: { full: "Our flight leaves at six in the morning.",
    pos: ["Our flight departs at 6 am.", "Our flight takes off at six in the morning.", "Our flight is leaving at 6:00 in the morning."],
    neg: ["Our flight will leave at six in the morning.", "Our flight leave at six in the morning.", "Our flight leaves at six of the morning.", "Our flight leaves on six in the morning.", "Our flight left at six in the morning.", "Our flight leaves at seven in the morning."] },

  review_l3_0: { full: "I think it will snow tonight.",
    pos: ["I think it's going to snow tonight.", "I think it'll snow this evening.", "Tonight I think it will snow."],
    neg: ["I think it snows tonight.", "I think it will snows tonight.", "I think will snow tonight.", "I think it will to snow tonight.", "I think it will snow last night.", "I think it will snowing tonight."] },
  review_l3_1: { full: "Look! The bus is going to leave without us.",
    pos: ["Look! The bus is leaving without us.", "Look, the bus's going to go without us"],
    neg: ["Look! The bus will leave without us.", "Look! The bus leaves without us.", "Look! The bus is going to leave with us.", "Look! The bus going to leave without us.", "Look! The bus is going to leaving without us.", "Look! The bus is going to leave us without."] },
  review_l3_2: { full: "At ten tomorrow I will be doing an exam.",
    pos: ["Tomorrow at ten I'll be taking an exam.", "I will be doing an exam at ten tomorrow.", "Tomorrow at 10 I'll be sitting a test."],
    neg: ["At ten tomorrow I will do an exam.", "At ten tomorrow I will be making an exam.", "At ten tomorrow I will be do an exam.", "At ten tomorrow I am doing an exam.", "At ten tomorrow I will doing an exam.", "At ten yesterday I will be doing an exam."] },
  review_l3_3: { full: "By June I will have passed my driving test.",
    pos: ["I'll have passed my driving test by June.", "By June I will have got my driving licence.", "By June Ill have passed the driving test"],
    neg: ["By June I will pass my driving test.", "By June I will have pass my driving test.", "By June I will have approved my driving test.", "By June I have passed my driving test.", "For June I will have passed my driving test.", "Until June I will have passed my driving test."] },
  review_l3_4: { full: "The film starts at half past nine.",
    pos: ["The movie begins at nine thirty.", "The film starts at 9:30.", "The film is starting at half past nine."],
    neg: ["The film will start at half past nine.", "The film start at half past nine.", "The film starts at nine and half.", "The film starts on half past nine.", "The film started at half past nine.", "The film starts at half to nine."] },
  review_l3_5: { full: "I am going out with my friends tonight.",
    pos: ["Tonight I'm going to go out with my friends.", "I'm going out with my friends this evening."],
    neg: ["I go out with my friends tonight.", "I am go out with my friends tonight.", "I going out with my friends tonight.", "I am going out with my friends last night.", "I am leaving with my friends tonight.", "I am going out my friends with tonight."] },
  review_l3_6: { full: "I will tell you when I know.",
    pos: ["When I find out, I'll tell you.", "I'll tell you when I know."],
    neg: ["I will tell you when I will know.", "I tell you when I know.", "I will say you when I know.", "I will tell you when I knew.", "I will tell to you when I know.", "I will telling you when I know."] },
  review_l3_7: { full: "Do not worry, I will help you.",
    pos: ["Don't worry, I'll help you.", "Dont worry Ill help you"],
    neg: ["Don't worry, I help you.", "Don't worry, I will help to you.", "Don't worry, I will helping you.", "Not worry, I will help you.", "Don't worry you, I will help you.", "Don't worry, I will to help you."] },
  review_l3_8: { full: "Will you be using the bike this afternoon?",
    pos: ["Are you going to use the bike this evening?", "Are you using the bicycle this afternoon?"],
    neg: ["Do you use the bike this afternoon?", "Will you be use the bike this afternoon?", "Will you using the bike this afternoon?", "You will be using the bike this afternoon?", "Will you be using the bike yesterday afternoon?", "Will you use the bike this afternoon?"] },
  review_l3_9: { full: "When I am 18, I will have finished secondary school.",
    pos: ["When I turn 18, I'll have finished high school.", "I will have finished secondary school when I am eighteen.", "By the time I'm 18 I'll have left school."],
    neg: ["When I will be 18, I will have finished secondary school.", "When I have 18, I will have finished secondary school.", "When I am 18, I will finish secondary school.", "When I am 18, I will have finish secondary school.", "When I am 18 years, I will have finished secondary school.", "When I am 18, I have finished secondary school."] }
};
